import turtle as t
t.speed(0)
t.pensize(1)
t.hideturtle()
t.setup(width=700.0 , height=700.0)
t.begin_fill()
t.fillcolor('yellow')
t.forward(200)
t.right(90)
t.forward(200)
t.right(90)
t.forward(200)
t.right(90)
t.forward(200)
t.end_fill()

t.penup()
t.goto(-100,0)
t.pendown()
t.begin_fill()
t.fillcolor('blue')
t.forward(-200)
t.right(90)
t.forward(-200)
t.right(90)
t.forward(-200)
t.right(90)
t.forward(-200)
t.end_fill()

t.penup()
t.goto(-100,300)
t.pendown()
t.begin_fill()
t.fillcolor('red')
t.forward(200)
t.left(90)
t.forward(200)
t.left(90)
t.forward(200)
t.left(90)
t.forward(200)
t.end_fill()

t.penup()
t.goto(200,300)
t.pendown()
t.begin_fill()
t.fillcolor('green')
t.forward(-200)
t.right(90)
t.forward(-200)
t.right(90)
t.forward(-200)
t.right(90)
t.forward(-200)
t.end_fill()

t.penup()
t.goto(0,0)
t.pendown()
t.backward(-100)
t.right(135)
t.begin_fill()
t.fillcolor('blue')
t.forward(70)
t.right(90)
t.forward(70)
t.end_fill()

t.left(135)
t.begin_fill()
t.fillcolor('yellow')
t.forward(100)
t.left(135)
t.forward(70)
t.end_fill()

t.right(90)
t.begin_fill()
t.fillcolor('red')
t.forward(70)
t.left(135)
t.forward(100)
t.end_fill()

t.penup()
t.goto(-100,100)
t.pendown()
t.left(90)
t.begin_fill()
t.fillcolor('green')
t.forward(100)
t.right(135)
t.forward(70)
t.end_fill()

t.penup()
t.goto(130,-40)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(40,-40)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(130,-120)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(40,-120)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(-170,-40)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(-260,-40)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(-170,-120)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(-260,-120)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(-260,180)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(-170,180)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(-260,260)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(-170,260)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(130,180)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(40,180)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(130,260)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(40,260)
t.pendown()
t.begin_fill()
t.fillcolor('white')
t.circle(20)
t.end_fill()

t.penup()
t.goto(0,300)
t.pendown()
t.right(45)
t.forward(100)

t.penup()
t.goto(-300,0)
t.pendown()
t.right(90)
t.forward(100)

t.penup()
t.goto(200,0)
t.pendown()
t.right(0)
t.forward(100)

t.penup()
t.goto(0,-200)
t.pendown()
t.left(90)
t.forward(100)

t.penup()
t.goto(-100,300)
t.pendown()
t.right(180)

t.speed(0)
t.pensize(1)


def draw_grid1(x, y, rows, cols, size):
    t.penup()
    t.goto(x, y)
    t.pendown()
    for r in range(rows):
        for c in range(cols):
            
            t.penup()
            t.goto(x + c*size, y - r*size)  
            t.pendown()
            for _ in range(4):  
                t.forward(size)
                t.right(90)
    t.penup()


start_x = -100   
start_y = 300    
square_size = 33 
rows = 6       
cols = 3        

draw_grid1(start_x, start_y, rows, cols, square_size)

def draw_grid2(x, y, rows, cols, size):
    t.penup()
    t.goto(x, y)
    t.pendown()
    for r in range(rows):
        for c in range(cols):
            
            t.penup()
            t.goto(x + c*size, y - r*size)  
            t.pendown()
            for _ in range(4):  
                t.forward(size)
                t.right(90)
    t.penup()


start_x = 0  
start_y = 100    
square_size = 33 
rows = 3       
cols = 6       

draw_grid2(start_x, start_y, rows, cols, square_size)

def draw_grid3(x, y, rows, cols, size):
    t.penup()
    t.goto(x, y)
    t.pendown()
    for r in range(rows):
        for c in range(cols):
            
            t.penup()
            t.goto(x + c*size, y - r*size)  
            t.pendown()
            for _ in range(4):  
                t.forward(size)
                t.right(90)
    t.penup()


start_x = -100  
start_y = 0    
square_size = 33 
rows = 6       
cols = 3      

draw_grid3(start_x, start_y, rows, cols, square_size)

def draw_grid4(x, y, rows, cols, size):
    t.penup()
    t.goto(x, y)
    t.pendown()
    for r in range(rows):
        for c in range(cols):
            
            t.penup()
            t.goto(x + c*size, y - r*size)  
            t.pendown()
            for _ in range(4):  
                t.backward(size)
                t.right(90)
    t.penup()


start_x = -267
start_y = 67
square_size = 33 
rows = 3       
cols = 6     

draw_grid4(start_x, start_y, rows, cols, square_size)

t.penup()
t.goto(-100,-166)
t.pendown()
t.fillcolor('blue')
t.begin_fill()
t.forward(66)
t.left(90)
t.forward(166)
t.left(90)
t.forward(33)
t.left(90)
t.forward(133)
t.right(90)
t.forward(33)
t.end_fill()

t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.right(90)
t.forward(33)
t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.right(90)
t.forward(33)
t.right(90)
t.forward(33)
t.left(90)
t.forward(33)
t.left(90)
t.forward(33)

t.penup()
t.goto(-266,100)
t.pendown()
t.begin_fill()
t.fillcolor('red')
t.left(90)
t.forward(66)
t.left(90)
t.forward(166)
t.left(90)
t.forward(33)
t.left(90)
t.forward(133)
t.right(90)
t.forward(33)
t.end_fill()

t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.right(90)
t.forward(33)
t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.right(90)
t.forward(33)
t.right(90)
t.forward(33)
t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.right(90)
t.forward(33)

t.penup()
t.goto(166,0)
t.pendown()
t.begin_fill()
t.fillcolor('yellow')
t.left(90)
t.forward(66)
t.left(90)
t.forward(166)
t.left(90)
t.forward(33)
t.left(90)
t.forward(133)
t.right(90)
t.forward(33)
t.end_fill()

t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.right(90)
t.forward(33)
t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.right(90)
t.forward(33)
t.right(90)
t.forward(33)
t.left(90)
t.forward(33)
t.left(90)
t.forward(33)

t.penup()
t.goto(0,266)
t.pendown()
t.begin_fill()
t.fillcolor('green')
t.right(90)
t.forward(66)
t.left(90)
t.forward(166)
t.left(90)
t.forward(33)
t.left(90)
t.forward(133)
t.right(90)
t.forward(33)
t.end_fill()

t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.right(90)
t.forward(33)
t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.right(90)
t.forward(33)
t.right(90)
t.forward(33)
t.left(90)
t.forward(33)
t.left(90)
t.forward(33)
t.done()


